name       : movit
version    : 1.6.2
release    : 5
source     :
    - https://movit.sesse.net/movit-1.6.2.tar.gz : 7428d56c23a38224c9333b8bb4a0c4f6b171ba64d4799c16516d40b30d0230e1
    - https://github.com/google/googletest/archive/release-1.8.0.tar.gz : 58a6f4277ca2bc8565222b3bbd58a177609e9c488e8a72649359ba51450db7d8
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : High-performance, high-quality video filters for the GPU
description: |
    High-performance, high-quality video filters for the GPU.
builddeps  :
    - pkgconfig(eigen3)
    - pkgconfig(epoxy)
    - pkgconfig(fftw3)
    - pkgconfig(gl)
    - pkgconfig(SDL2_image)
    - pkgconfig(x11)
    - gtest-devel
setup      : |
    # Extract gtest sources which are unfortunately required...
    tar xf $sources/release-* -C .
    %configure
build      : |
    %make GTEST_DIR='${workdir}/googletest-release-1.8.0/googletest'
install    : |
    %make_install
