name       : movit
version    : 1.6.3
release    : 7
source     :
    - https://movit.sesse.net/movit-1.6.3.tar.gz : eb19f109ec99d6050de5267d059c7b351d3d5e39c77d43ca348a95f474a99498
    - https://github.com/google/googletest/archive/release-1.12.1.tar.gz : 81964fe578e9bd7c94dfdb09c8e4d6e6759e19967e397dbea48d1c10e45d0df2
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : High-performance, high-quality video filters for the GPU
description: |
    High-performance, high-quality video filters for the GPU.
builddeps  :
    - pkgconfig(SDL2_image)
    - pkgconfig(eigen3)
    - pkgconfig(epoxy)
    - pkgconfig(fftw3)
    - pkgconfig(gl)
    - pkgconfig(x11)
    - gtest-devel
setup      : |
    %apply_patches
    # Extract gtest sources which are unfortunately required...
    tar xf $sources/release-* -C .
    %configure
build      : |
    %make GTEST_DIR='${workdir}/googletest-release-1.12.1/googletest'
install    : |
    %make_install
